apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: certificado
      server: SERVER
    name: eks-devsu
contexts:
  - context:
      cluster: eks-devsu
      user: azure-devops-sa
    name: eks-devsu-context
current-context: eks-devsu-context
users:
  - name: azure-devops-sa
    user:
      token: TOKEN
