trigger:
  branches:
    include:
      - main
      - release
      - develop
  paths:
    exclude:
      - azure-pipelines.yml

name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      - name: enviroment-suffix
        value: dev
      - name: poolName
        value: BryanPool
      - group: PruebaDesa
  - ${{ else }}:
      - name: enviroment-suffix
        value: dev
      - name: poolName
        value: BryanPool
      - group: PruebaDesa

  - ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
      - name: enviroment-suffix
        value: qa
      - name: poolName
        value: BryanPool
      - group: PruebaDesa

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - name: enviroment-suffix
        value: prod
      - name: poolName
        value: BryanPool
      - group: PruebaDesa

stages:
  - stage: Analisis
    jobs:
      - job: Analisis
        pool:
          name: $(poolName)
        steps:
          - checkout: self

          - task: SonarCloudPrepare@4
            inputs:
              SonarQube: "SonarQube-svc"
              organization: "bryanavalos23-1"
              cliProjectKey: $(cliProjectKey)
              scannerMode: "cli"
              cliScannerVersion: "8.1.0.6389"
              configMode: "manual"
              extraProperties: |
                sonar.javascript.lcov.reportPaths=coverage/lcov.info

          - script: |
              echo "Haciendo build del proyecto"
              npm install
            displayName: "Npm install"

          - script: |
              echo "Haciendo test del proyecto"
              npm test -- --coverage
            displayName: "Test"

          - task: SonarCloudAnalyze@4
            displayName: "Analisis"

          - task: SonarCloudPublish@4
            inputs:
              pollingTimeoutSec: "300"
            displayName: "Publicar resultados"

  - stage: BuildAndPushImage
    dependsOn: Analisis
    jobs:
      - job: Build
        pool:
          name: $(poolName)
        steps:
          - checkout: self

          - script: |
              aws ecr get-login-password --region us-east-1 \
              | docker login \
                --username AWS \
                --password-stdin \
                $(AWS_ACCOUNT_ID).dkr.ecr.us-east-1.amazonaws.com
            displayName: "ECR Login"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

          - task: Docker@2
            inputs:
              repository: $(repository)
              command: "build"
              Dockerfile: "Dockerfile"
              tags: "latest"
            displayName: "Build Docker Image"

          - task: Docker@2
            inputs:
              repository: $(repository)
              command: "push"
              tags: "latest"
            displayName: "Push Docker Image"

  - stage: Deploy
    dependsOn: BuildAndPushImage
    jobs:
      - job: Deploy
        pool:
          name: $(poolName)
        steps:
          - checkout: self
          - task: replacetokens@7
            inputs:
              root: "$(Build.SourcesDirectory)"
              sources: "k8s/*.yml"
              tokenPattern: "azpipelines"
              encoding: "utf-8"
            displayName: "Replace Tokens"

          - script: |
              aws eks update-kubeconfig \
                --region us-east-1 \
                --name devsu-demo-app-eks-cluster
              kubectl get nodes
            displayName: "Verificar conexion con EKS"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: us-east-1

          - task: Kubernetes@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "eks-demo-app-node"
              namespace: "demo-app"
              command: "apply"
              useConfigurationFile: true
              configuration: "k8s/deployment.yml"
              arguments: "--validate=false"
            displayName: "apply deployment"

          - task: Kubernetes@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "eks-demo-app-node"
              namespace: "demo-app"
              command: "apply"
              useConfigurationFile: true
              configuration: k8s/services.yml
              arguments: "--validate=false"
            displayName: "Apply service"

          - task: Kubernetes@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "eks-demo-app-node"
              namespace: "demo-app"
              command: "apply"
              useConfigurationFile: true
              configuration: k8s/ingress.yml
              arguments: "--validate=false"
            displayName: "Apply ingress"

          - task: Kubernetes@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceEndpoint: "eks-demo-app-node"
              namespace: "demo-app"
              command: "apply"
              useConfigurationFile: true
              configuration: k8s/hpa.yml
              arguments: "--validate=false"
            displayName: "Apply HPA"

          - script: |
              aws eks update-kubeconfig \
                --region us-east-1 \
                --name devsu-demo-app-eks-cluster
              kubectl get pods -n $(namespace) -o wide
            displayName: "Verificar pods"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: us-east-1
