services:
  app:
    image: bryanavalos/prueba-tecnica:1.1
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - NODE_ENV=${NODE_ENV}
    networks:
      - prueba-tecnica

networks:
  prueba-tecnica:
    external: true